name: florence
description: AI-Enabled Digital Health Platform for Chronic Disease Monitoring

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider:

  # Backend & API
  supabase_flutter:
  http:
  flutter_markdown:

  # Data Visualization
  fl_chart:

  # Data Serialization
  json_annotation:

  # Date & Time Handling
  intl:
  table_calendar:

  # Image Handling
  image_picker:
  cached_network_image:

  # iOS Style Icons
  cupertino_icons:

  # Deep Linking
  app_links:

  # SVG Support
  flutter_svg:

  # Local Storage
  shared_preferences:

  # Fonts
  google_fonts:
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

  # Code Generation
  build_runner:
  json_serializable:

  change_app_package_name:

  flutter_app_name:

flutter:

  uses-material-design: true
  assets:
    - shorebird.yaml

flutter_app_name:
  name: "Florence"
