name: florence_platform
description: BioTective Patient Dashboard - Digital Health Platform for Chronic Disease Monitoring

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Backend & API
  supabase_flutter: ^2.3.4
  http: ^1.2.0

  # Data Visualization
  fl_chart: ^0.66.0

  # Data Serialization
  json_annotation: ^4.8.1

  # Date & Time Handling
  intl: ^0.19.0
  table_calendar: ^3.0.9

  # Image Handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.8
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true